const routers = [
  {
    path: "/",
    redirect: "/auth",
  },
  {
    component: "AuthLayout",
    path: "/auth",
    auth: false,
    name: "Auth",
    exact: false,
    redirect: "/auth/login",
    childrens: [
      {
        component: "Login",
        path: "/login",
        componentPath: "pages/Auth/Login",
        name: "Login",
        auth: false,
        exact: true,
      },
      {
        component: "ForgetPassword",
        path: "/forget",
        componentPath: "pages/Auth/ForgetPassword",
        name: "ForgetPassword",
        auth: false,
        exact: true,
      },
      {
        component: "ResetPassword",
        path: "/resetpassword",
        componentPath: "pages/Auth/ResetPassword",
        name: "ResetPassword",
        auth: false,
        exact: true,
      },
      {
        component: "Disclaimer",
        path: "/disclaimer",
        componentPath: "pages/Auth/Disclaimer",
        name: "Disclaimer",
        auth: false,
        exact: true,
      },
      {
        component: "Blogs",
        path: "/blogs",
        componentPath: "pages/Auth/Blogs",
        name: "Blogs",
        auth: false,
        exact: true,
      },
    ],
  },
  {
    component: "MainLayout",
    path: "/admin",
    auth: false,
    name: "Dashboard",
    exact: false,
    redirect: "/admin/dashboard",
    childrens: [
      // DASHBOARD
      {
        component: "Dashboard",
        path: "/dashboard",
        componentPath: "pages/Dashboard/InitDashboard/Dashboard",
        name: "Dashboard",
        auth: false,
        exact: true,
      },
      {
        component: "StaffManagement",
        path: "/staff-management",
        componentPath: "pages/Dashboard/StaffManagement/StaffManagement",
        name: "StaffManagement",
        auth: false,
        exact: true,
      },
      {
        component: "AddStaffManagement",
        path: "/staff-management/add-staff",
        componentPath: "pages/Dashboard/StaffManagement/AddStaffManagement",
        name: "AddStaffManagement",
        auth: false,
        exact: true,
      },
      {
        component: "ProductManagement",
        path: "/product-management",
        componentPath: "pages/Dashboard/ProductManagement/ProductManagement",
        name: "ProductManagement",
        auth: false,
        exact: true,
      },

      {
        component: "NotificationManagement",
        path: "/notification-management",
        componentPath:
          "pages/Dashboard/NotificationManagement/NotificationManagement",
        name: "NotificationManagement",
        auth: false,
        exact: true,
      },
      {
        component: "AddProduct",
        path: "/product-management/add-product",
        componentPath: "pages/Dashboard/ProductManagement/AddProduct",
        name: "AddProduct",
        auth: false,
        exact: true,
      },

      {
        component: "FeedbackManagement",
        path: "/feedback-management",
        componentPath: "pages/Dashboard/FeedbackManagement/FeedbackManagement",
        name: "FeedbackManagement",
        auth: false,
        exact: true,
      },
      {
        component: "AddFeedback",
        path: "/feedBack-management/add-feedback",
        componentPath: "pages/Dashboard/FeedbackManagement/AddFeedback",
        name: "AddFeedback",
        auth: false,
        exact: true,
      },
      {
        component: "LeadManagement",
        path: "/lead-management",
        componentPath: "pages/Dashboard/LeadManagement/LeadManagement",
        name: "LeadManagement",
        auth: false,
        exact: true,
      },
      {
        component: "AnswerFeedback",
        path: "/feedBack-management/answer-feedback",
        componentPath: "pages/Dashboard/FeedbackManagement/AnswerFeedback",
        name: "AnswerFeedback",
        auth: false,
        exact: true,
      },

      {
        component: "CreateNotification",
        path: "/notification-management/create-notification",
        componentPath:
          "pages/Dashboard/NotificationManagement/CreateNotification",
        name: "CreateNotification",
        auth: false,
        exact: true,
      },
      {
        path: "/notification-management/send-notification",
        componentPath:
          "pages/Dashboard/NotificationManagement/SendNotification",
        name: "SendNotification",
        auth: false,
        exact: true,
      },
      {
        component: "ContentManagement",
        path: "/content-management",
        componentPath: "pages/Dashboard/ContentManagement/ContentManagement",
        name: "ContentManagement",
        auth: false,
        exact: true,
      },
      {
        component: "IpoManagement",
        path: "/ipo-management",
        componentPath: "pages/Dashboard/IpoManagement/IpoManagement",
        name: "IpoManagement",
        auth: false,
        exact: true,
      },
      {
        component: "EditIpoManagement",
        path: "/ipo-management/edit-ipo",
        componentPath: "pages/Dashboard/IpoManagement/EditIpoManagement",
        name: "EditIpoManagement",
        auth: false,
        exact: true,
      },
      {
        component: "EditContentManagement",
        path: "/content-management/editContent-management",
        componentPath: "pages/Dashboard/ContentManagement/EditContentManagement",
        name: "EditContentManagement",
        auth: false,
        exact: true,
      },
      {
        component: "FaqManagement",
        path: "/faq-management",
        componentPath: "pages/Dashboard/FaqManagement/FaqManagement",
        name: "FaqManagement",
        auth: false,
        exact: true,
      },
      {
        component: "AddFaq",
        path: "/faq-management/add-faq",
        componentPath: "pages/Dashboard/FaqManagement/AddFaq",
        name: "AddFaq",
        auth: false,
        exact: true,
      },
      {
        component: "FeeManagement",
        path: "/fee-management",
        componentPath: "pages/Dashboard/FeeManagement/FeeManagement",
        name: "FeeManagement",
        auth: false,
        exact: true,
      },
      {
        component: "ApManagement",
        path: "/ap-management",
        componentPath: "pages/Dashboard/ApManagement/ApManagement",
        name: "ApManagement",
        auth: false,
        exact: true,
      },
      {
        component: "ViewApManagement",
        path: "/ap-management/view-ap-management",
        componentPath: "pages/Dashboard/ApManagement/ViewApManagement",
        name: "ViewApManagement",
        auth: false,
        exact: true,
      },
      {
        component: "AddFee",
        path: "/fee-management/add-fee",
        componentPath: "pages/Dashboard/FeeManagement/AddFee",
        name: "AddFee",
        auth: false,
        exact: true,
      },
      {
        component: "KnowledgeCenter",
        path: "/knowledge-center",
        componentPath:
          "pages/Dashboard/KnowledgeCenter/KnowledgeCenter",
        name: "KnowledgeCenter",
        auth: false,
        exact: true,
      },


      {
        component: "TemplateManagement",
        path: "/template-management",
        componentPath: "pages/Dashboard/TemplateManagement/TemplateManagement",
        name: "TemplateManagement",
        auth: false,
        exact: true,
      },
      {
        component: "AddTemplateManagement",
        path: "/template-management/add-template",
        componentPath: "pages/Dashboard/TemplateManagement/AddTemplateManagement",
        name: "AddTemplateManagement",
        auth: false,
        exact: true,
      },
      {
        component: "SiteSetting",
        path: "/site-settings",
        componentPath: "pages/Dashboard/SiteSetting/SiteSetting",
        name: "SiteSetting",
        auth: false,
        exact: true,
      },
      {
        component: "AddKnowledge",
        path: "/knowledge-center/add-knowledge",
        componentPath:
          "pages/Dashboard/KnowledgeCenter/AddKnowledge",
        name: "AddKnowledge",
        auth: false,
        exact: true,
      },
      {
        component: "ClientsFamily",
        path: "/clients-family",
        componentPath:
          "pages/Dashboard/ClientsFamilyPage/ClientsFamilyPage",
        name: "ClientsFamily",
        auth: false,
        exact: true,
      },
      {
        component: "EditClientsFamily",
        path: "/clients-family/edit-client",
        componentPath:
          "pages/Dashboard/ClientsFamilyPage/EditClientsFamily",
        name: "EditClientsFamily",
        auth: false,
        exact: true,
      },
      {
        component: "CalendarManagement",
        path: "/calendar-management",
        componentPath: "pages/Dashboard/CalendarManagement/CalendarManagement",
        name: "CalendarManagement",
        auth: false,
        exact: true,
      },
      {
        component: "AddCalendarManagement",
        path: "/calendar-management/add-calendar",
        componentPath: "pages/Dashboard/CalendarManagement/AddCalendarManagement",
        name: "AddCalendarManagement",
        auth: false,
        exact: true,
      },
    ],
  },
];
export default routers;
